- name: Run Nginx as reverse proxy
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Assurez-vous que vous avez une configuration de proxy inversé appropriée

